/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assets */
        get: operations["assets_api_assets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets/{symbol}/range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Asset Range
         * @description Return the date range the UI can use as min/max on date inputs.
         *
         *     Sourced from the local SQLite cache when populated, falling back
         *     to a hardcoded earliest-available date per symbol when the cache
         *     is empty (fresh install). Avoids hitting yfinance just to discover
         *     the floor.
         */
        get: operations["asset_range_api_assets__symbol__range_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Strategies */
        get: operations["strategies_api_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommendations/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recommendation */
        post: operations["recommendation_api_recommendations_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimizations/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Optimization */
        post: operations["optimization_api_optimizations_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimizations/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Optimization */
        post: operations["create_optimization_api_optimizations_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/optimizations/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Optimization Status */
        get: operations["optimization_status_api_optimizations_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Cancel Optimization */
        delete: operations["cancel_optimization_api_optimizations_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtests/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Backtest */
        post: operations["backtest_api_backtests_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Asset */
        Asset: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /**
             * Market
             * @default us
             */
            market: string;
            /**
             * Category
             * @default core_us
             */
            category: string;
            /**
             * Categorylabel
             * @default 核心宽基
             */
            categoryLabel: string;
            /**
             * Risklevel
             * @default core
             * @enum {string}
             */
            riskLevel: "core" | "advanced";
            /** Risknote */
            riskNote?: string | null;
        };
        /** AssetRange */
        AssetRange: {
            /** Symbol */
            symbol: string;
            /**
             * Mindate
             * Format: date
             */
            minDate: string;
            /**
             * Maxdate
             * Format: date
             */
            maxDate: string;
        };
        /** BacktestMetrics */
        BacktestMetrics: {
            /** Totalinvested */
            totalInvested: number;
            /** Endingvalue */
            endingValue: number;
            /** Returnpct */
            returnPct: number;
            /** Annualizedreturnpct */
            annualizedReturnPct: number;
            /** Maxdrawdownpct */
            maxDrawdownPct: number;
            /** Buycount */
            buyCount: number;
            /** Avgcontribution */
            avgContribution: number;
            /** Versusfixedpct */
            versusFixedPct?: number | null;
            /** Versuslumpsumpct */
            versusLumpSumPct?: number | null;
            /** Sharperatio */
            sharpeRatio?: number | null;
            /** Sortinoratio */
            sortinoRatio?: number | null;
        };
        /** BacktestRequest */
        BacktestRequest: {
            /**
             * Symbol
             * @default QQQ
             */
            symbol: string;
            config?: components["schemas"]["StrategyConfig"];
            /** Startdate */
            startDate?: string | null;
            /** Enddate */
            endDate?: string | null;
            /** Comparisonstrategytypes */
            comparisonStrategyTypes?: string[];
            /**
             * Riskfreerate
             * @description Annualized risk-free rate used for Sharpe/Sortino. Default 4% reflects roughly the 2024 short-term US treasury yield.
             * @default 0.04
             */
            riskFreeRate: number;
        };
        /** BacktestResult */
        BacktestResult: {
            /** Symbol */
            symbol: string;
            /** Strategytype */
            strategyType: string;
            recommendation: components["schemas"]["StrategyDecision"];
            metrics: components["schemas"]["BacktestMetrics"];
            fixedMetrics?: components["schemas"]["BacktestMetrics"] | null;
            lumpSumMetrics?: components["schemas"]["BacktestMetrics"] | null;
            marketState?: components["schemas"]["MarketState"] | null;
            /** Contributions */
            contributions: components["schemas"]["ContributionEvent"][];
            /** Fixedcontributions */
            fixedContributions?: components["schemas"]["ContributionEvent"][];
            /** Lumpsumcontributions */
            lumpSumContributions?: components["schemas"]["ContributionEvent"][];
            /** Strategycomparisons */
            strategyComparisons?: components["schemas"]["StrategyComparison"][];
            /** Priceseries */
            priceSeries: components["schemas"]["PricePoint"][];
            /** Datasource */
            dataSource: string;
            /** Cachestatus */
            cacheStatus: string;
        };
        /** ContributionEvent */
        ContributionEvent: {
            /** Date */
            date: string;
            /** Price */
            price: number;
            /** Amount */
            amount: number;
            /**
             * Shares
             * @description Shares bought in this contribution event, not cumulative shares.
             */
            shares: number;
            /** Totalshares */
            totalShares: number;
            /** Totalinvested */
            totalInvested: number;
            /** Portfoliovalue */
            portfolioValue: number;
            /** Multiplier */
            multiplier: number;
            /** Score */
            score: number;
            /** Reasons */
            reasons: string[];
            /**
             * Drawdownpct
             * @default 0
             */
            drawdownPct: number;
            /** Accountdrawdownpct */
            accountDrawdownPct?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MarketState */
        MarketState: {
            /** Label */
            label: string;
            /**
             * Tone
             * @enum {string}
             */
            tone: "up" | "down" | "neutral";
            /** Summary */
            summary: string;
            /** Price */
            price?: number | null;
            /** Sma50 */
            sma50?: number | null;
            /** Sma200 */
            sma200?: number | null;
            /** Distancetosma200Pct */
            distanceToSma200Pct?: number | null;
        };
        /** OptimizationCandidate */
        OptimizationCandidate: {
            /** Rank */
            rank: number;
            /** Score */
            score: number;
            config: components["schemas"]["StrategyConfig"];
            /** Scenarios */
            scenarios: components["schemas"]["OptimizationScenarioMetrics"][];
            summary: components["schemas"]["BacktestMetrics"];
        };
        /** OptimizationJobCreateResponse */
        OptimizationJobCreateResponse: {
            /** Jobid */
            jobId: string;
        };
        /** OptimizationJobStatus */
        OptimizationJobStatus: {
            /** Jobid */
            jobId: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed" | "cancelled";
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Evaluatedcount
             * @default 0
             */
            evaluatedCount: number;
            /**
             * Totalcount
             * @default 0
             */
            totalCount: number;
            /** Currentscenario */
            currentScenario?: string | null;
            bestSoFar?: components["schemas"]["OptimizationCandidate"] | null;
            result?: components["schemas"]["OptimizationResult"] | null;
            /** Error */
            error?: string | null;
        };
        /** OptimizationRequest */
        OptimizationRequest: {
            /**
             * Symbol
             * @default QQQ
             */
            symbol: string;
            config?: components["schemas"]["StrategyConfig"];
            /** Startdate */
            startDate?: string | null;
            /** Enddate */
            endDate?: string | null;
            /**
             * Objective
             * @default robust_return
             * @enum {string}
             */
            objective: "robust_return" | "max_return" | "min_drawdown";
        };
        /** OptimizationResult */
        OptimizationResult: {
            /** Symbol */
            symbol: string;
            /**
             * Objective
             * @enum {string}
             */
            objective: "robust_return" | "max_return" | "min_drawdown";
            baselineConfig: components["schemas"]["StrategyConfig"];
            recommendedConfig: components["schemas"]["StrategyConfig"];
            baselineSummary: components["schemas"]["BacktestMetrics"];
            recommendedSummary: components["schemas"]["BacktestMetrics"];
            /** Candidates */
            candidates: components["schemas"]["OptimizationCandidate"][];
            /** Scenarios */
            scenarios: components["schemas"]["OptimizationScenarioResult"][];
            /** Searchedcount */
            searchedCount: number;
            /** Skippedcount */
            skippedCount: number;
        };
        /** OptimizationScenarioMetrics */
        OptimizationScenarioMetrics: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Startdate
             * Format: date
             */
            startDate: string;
            /**
             * Enddate
             * Format: date
             */
            endDate: string;
            metrics: components["schemas"]["BacktestMetrics"];
            fixedMetrics: components["schemas"]["BacktestMetrics"];
            /** Score */
            score: number;
        };
        /** OptimizationScenarioResult */
        OptimizationScenarioResult: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Startdate
             * Format: date
             */
            startDate: string;
            /**
             * Enddate
             * Format: date
             */
            endDate: string;
            baselineMetrics: components["schemas"]["BacktestMetrics"];
            recommendedMetrics: components["schemas"]["BacktestMetrics"];
            fixedMetrics: components["schemas"]["BacktestMetrics"];
        };
        /** ParameterOption */
        ParameterOption: {
            /** Label */
            label: string;
            /** Value */
            value: string | number | boolean;
        };
        /** PricePoint */
        PricePoint: {
            /** Date */
            date: string;
            /** Close */
            close: number;
        };
        /** RecommendationRequest */
        RecommendationRequest: {
            /**
             * Symbol
             * @default QQQ
             */
            symbol: string;
            config?: components["schemas"]["StrategyConfig"];
            /** Asof */
            asOf?: string | null;
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /** Symbol */
            symbol: string;
            decision: components["schemas"]["StrategyDecision"];
            /** Datasource */
            dataSource: string;
            /** Cachestatus */
            cacheStatus: string;
        };
        /** StrategyComparison */
        StrategyComparison: {
            /** Strategytype */
            strategyType: string;
            /** Name */
            name: string;
            metrics: components["schemas"]["BacktestMetrics"];
            /** Contributions */
            contributions: components["schemas"]["ContributionEvent"][];
        };
        /** StrategyConfig */
        StrategyConfig: {
            /**
             * Strategytype
             * @default composite_score
             */
            strategyType: string;
            /**
             * Baseamount
             * @default 100
             */
            baseAmount: number;
            /**
             * Frequency
             * @default weekly
             * @enum {string}
             */
            frequency: "weekly" | "biweekly" | "monthly";
            /**
             * Minmultiplier
             * @default 0.8
             */
            minMultiplier: number;
            /**
             * Maxmultiplier
             * @default 1.2
             */
            maxMultiplier: number;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
        };
        /** StrategyDecision */
        StrategyDecision: {
            /** Date */
            date: string;
            /** Price */
            price: number;
            /** Recommendedamount */
            recommendedAmount: number;
            /** Multiplier */
            multiplier: number;
            /** Score */
            score: number;
            /** Rawsignals */
            rawSignals: {
                [key: string]: number | string | null;
            };
            /** Reasons */
            reasons: string[];
            /**
             * Warmup
             * @default false
             */
            warmup: boolean;
        };
        /** StrategyDefinition */
        StrategyDefinition: {
            /** Type */
            type: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Parameters */
            parameters: components["schemas"]["StrategyParameter"][];
        };
        /** StrategyDefinitionsResponse */
        StrategyDefinitionsResponse: {
            /** Commonparameters */
            commonParameters: components["schemas"]["StrategyParameter"][];
            /** Strategies */
            strategies: components["schemas"]["StrategyDefinition"][];
        };
        /** StrategyParameter */
        StrategyParameter: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Type
             * @enum {string}
             */
            type: "number" | "range" | "select" | "toggle";
            /** Default */
            default: unknown;
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /** Step */
            step?: number | null;
            /** Options */
            options?: components["schemas"]["ParameterOption"][];
            /**
             * Help
             * @default
             */
            help: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    assets_api_assets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"][];
                };
            };
        };
    };
    asset_range_api_assets__symbol__range_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetRange"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    strategies_api_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyDefinitionsResponse"];
                };
            };
        };
    };
    recommendation_api_recommendations_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimization_api_optimizations_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_optimization_api_optimizations_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizationJobCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimization_status_api_optimizations_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizationJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_optimization_api_optimizations_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizationJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtest_api_backtests_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
